INSERT INTO CUENTAS(ID_CUENTA, CIF, NOMBRE, SITIO_WEB, ID_PROPIETARIO, FEC_INICIO_PROPIEDAD, FEC_FIN_PROPIEDAD, MARCAS, CANAL) VALUES ('1', '53666188J', 'Alfredo', 'www.alfredo.com', 'alfredo@email.com', '2022-02-04', '2022-02-04', 'marca, alfredoMarca', 'venta');
INSERT INTO cuentas(ID_CUENTA, CIF, NOMBRE, SITIO_WEB, ID_PROPIETARIO, FEC_INICIO_PROPIEDAD, FEC_FIN_PROPIEDAD, MARCAS, CANAL) VALUES ('2', '53666188J', 'Alfredo', 'www.alfredo.com', 'alfredo@email.com', '2022-02-04', '2022-02-04', 'AlfredoMarca', 'canalVenta');
INSERT INTO cuentas(ID_CUENTA, CIF, NOMBRE, SITIO_WEB, ID_PROPIETARIO, FEC_INICIO_PROPIEDAD, FEC_FIN_PROPIEDAD, MARCAS, CANAL) VALUES ('3', '53666188J', 'Alfredo', 'www.alfredo.com', 'alfredo@email.com', '2022-02-04', '2022-02-04', 'AlfredoMarca', 'canalVenta');
INSERT INTO cuentas(ID_CUENTA, CIF, NOMBRE, SITIO_WEB, ID_PROPIETARIO, FEC_INICIO_PROPIEDAD, FEC_FIN_PROPIEDAD, MARCAS, CANAL) VALUES ('4', '53666188J', 'Alfredo', 'www.alfredo.com', 'alfredo@email.com', '2022-02-04', '2022-02-04', 'AlfredoMarca', 'canalVenta');
INSERT INTO cuentas(ID_CUENTA, CIF, NOMBRE, SITIO_WEB, ID_PROPIETARIO, FEC_INICIO_PROPIEDAD, FEC_FIN_PROPIEDAD, MARCAS, CANAL) VALUES ('5', '53666188J', 'Alfredo', 'www.alfredo.com', 'alfredo@email.com', '2022-02-04', '2022-02-04', 'AlfredoMarca', 'canalVenta');

INSERT INTO cuentas(ID_CUENTA, CIF, NOMBRE, SITIO_WEB, ID_PROPIETARIO, FEC_INICIO_PROPIEDAD, FEC_FIN_PROPIEDAD, MARCAS, CANAL) VALUES ('6', '12366647L', 'Lucía', 'www.lucia.com', 'lucia@email.com', '2022-02-04', '2022-02-04', 'luciaMarca', 'canalVenta');
INSERT INTO cuentas(ID_CUENTA, CIF, NOMBRE, SITIO_WEB, ID_PROPIETARIO, FEC_INICIO_PROPIEDAD, FEC_FIN_PROPIEDAD, MARCAS, CANAL) VALUES ('7', '12366647L', 'Paula', 'www.paula.com', 'paula@email.com', '2022-02-04', '2022-02-04', 'paulaMarca', 'canalVenta');
INSERT INTO cuentas(ID_CUENTA, CIF, NOMBRE, SITIO_WEB, ID_PROPIETARIO, FEC_INICIO_PROPIEDAD, FEC_FIN_PROPIEDAD, MARCAS, CANAL) VALUES ('8', '12366647L', 'Pedro', 'www.pedro.com', 'pedro@email.com', '2022-02-04', '2022-02-04', 'pedroMarca', 'canalVenta');

INSERT INTO oferta(ID_OFERTA, ID_CUENTA, CONTENIDO, FEC_ALTA, ID_OFERTA_ORIGEN, ID_PROPIETARIO, ESTADO, FEC_ESTADO, VERSION) VALUES ('1', '1', 'Oferta interesante 1', '2022-02-04', '1', 'alfredo@email.com', 'CREADA', '2022-02-04', 1);
INSERT INTO oferta(ID_OFERTA, ID_CUENTA, CONTENIDO, FEC_ALTA, ID_OFERTA_ORIGEN, ID_PROPIETARIO, ESTADO, FEC_ESTADO, VERSION) VALUES ('2', '1', 'Oferta interesante 2', '2022-02-04', '1', 'alfredo@email.com', 'CREADA', '2022-02-04', 2);
INSERT INTO oferta(ID_OFERTA, ID_CUENTA, CONTENIDO, FEC_ALTA, ID_OFERTA_ORIGEN, ID_PROPIETARIO, ESTADO, FEC_ESTADO, VERSION) VALUES ('3', '1', 'Oferta interesante 3', '2022-02-04', '1', 'alfredo@email.com', 'CANCELADA', '2022-02-04', 1);

INSERT INTO cuenta_bancaria(ID_CUENTA_BANCARIA, ID_CUENTA, NUMERO_CUENTA) VALUES (1, 1, 1122334455);
INSERT INTO cuenta_bancaria(ID_CUENTA_BANCARIA, ID_CUENTA, NUMERO_CUENTA) VALUES (2, 1, 1234567890);
INSERT INTO cuenta_bancaria(ID_CUENTA_BANCARIA, ID_CUENTA, NUMERO_CUENTA) VALUES (3, 1, 9876543210);